contact_links:
  - name: Are you looking for documentation on palimpsest-bs?
    url: https://mtwente.github.io/palimpsest-bs
    about: Please see the documentation for palimpsest-bs on its GitHub Pages page.
  - name: Do want to discuss palimpsest-bs with the community?
    url: https://github.com/mtwente/palimpsest-bs/discussions
    about: Please see the discussions page for palimpsest-bs.
blank_issues_enabled: true
