on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Render and Publish

permissions:
  contents: write
  pages: write

jobs:
  build-deploy:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Overwrite _quarto.yml
        if: github.repository == 'maehr/open-research-data-template'
        run: |
          cp .github/_quarto.yml _quarto.yml

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tinytex: true

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: any::ggplot2
            any::plotly
            any::tidyr
            any::leaflet
            any::geojsonio

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: manuscript
          to: all

      - name: Install chromium
        run: |
          brew install --cask chromium

      - name: Convert html to pdf with Chromium
        run: |
          chromium --headless --disable-gpu --print-to-pdf=manuscript/_manuscript/palimpsest-bs.pdf  --scale=1.0 --no-pdf-header-footer --print-background --virtual-time-budget=10000 file:///$(pwd)/manuscript/_manuscript/index.html

      - name: Clean up
        run: |
          rm -rf ./palimpsest-bs_files/
          rm -rf ./_tex/

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          path: manuscript
          target: gh-pages
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
